### PR TITLE
Milestone Three

### PR DESCRIPTION
**Pull request by Berabjesus**
We have added the following.

- Dispatch Create and remove actions to dynamically add or remove books using useDispatch.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] All changes are implemented correctly, _however_ the app is not working, due to some errors in your App.js, you are naming `BookForm` and `BookList` => `BookFormComponent` and `BookListComponent` you have that extra word `Component` at the end which causes the issue, please always double-check the project before submitting for a review
- [x] `OPTIONAL` but highly recommended, follow the best naming practices on your project, all your components files should be capitalized, so `App.js` instead of `app.js` for example, and your folders should all have lower case letters, your `containers` folder has a `C` capitalized, unlike the rest of your folders. please take the time to apply these changes.

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by Berabjesus** [comment]
Thank you for the review. It is working locally regardless of the `component` name added. The reason it is not working on Heroku is that we forgot to push it to Heroku as well.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [x] Sorry this wasn't mentioned in the previous review but kindly include a getting started instructions section in the readme.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
